openapi: 3.0.0
info:
  title: API de agencia de Turismo.
  description: Esta API se encarga de manejar la información de los hoteles y vuelos ofrecidos por la agencia.
  version: 1.0.0
servers:
- url: localhost:8080/api/v1/hotels/
tags:
- name: Hoteles
  description: Información de los hoteles disponibles ofrecidos por la empresa.

paths:

  /findByDestination/{destination}:
    get:
      tags:
      - Hoteles
      summary: Muestra toda la información de hoteles filtrados por destino.
      parameters:
      - name: destination
        in: path
        description: Lugar en donde se quiere encontrar un hotel.
        required: true
        allowReserved: true
        schema:
          type: string
          
      responses:
        200:
          description: (OK) Consulta realizada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelesDestinationGet'
        400:
          $ref: '#/components/responses/BadRequest'
    
  /findByLowerPrice:
    get:
      tags:
      - Hoteles
      summary: Muestra todos los hoteles ofrecidos, ordenados de menor a mayor costo por noche.
      responses:
        200:
          description:  (OK) Consulta realizada.
          content:
            application/json:
              schema:
                properties:
                  lista de hoteles:
                    type: array
                    items:
                      $ref: '#/components/schemas/HotelesLowerCostGet'
                  
        400:
          $ref: '#/components/responses/BadRequest'
  
  /staySimulation:
    get:
      tags:
      - Hoteles
      summary: Simulación de una reserva de hotel.
      parameters:
        - in: query
          name: hotelCode
          required: true
          schema:
            type: string
          allowReserved: true
        - in: query
          name: days
          required: true
          schema:
            type: string
          allowReserved: true
        - in: query
          name: peopleAmount
          required: true
          schema:
            type: string
          allowReserved: true
        - in: query
          name: pay
          required: true
          schema:
            type: string
          allowReserved: true
        - in: query
          name: seat
          required: false
          schema:
            type: integer
          allowReserved: true
        
      responses:
        200:
          description: (OK) Consulta realizada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelesStaySimulation'
        400:
          $ref: '#/components/responses/BadRequest'
          
  /findByName/{hotelName}:
    get:
      tags:
      - Hoteles
      summary: Muestra toda la información de hoteles filtrados por destino.
      parameters:
      - name: hotelName
        in: path
        description: Nombre o letras para encontrar un hotel.
        required: true
        allowReserved: true
        schema:
          type: string
          
      responses:
        200:
          description: (OK) Consulta realizada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelFindByName'
        400:
          $ref: '#/components/responses/BadRequest'
  
components:
  responses:
    
    BadRequest:
      description: (Bad Request) Los datos enviados son incorrectos o hay datos obligatorios no enviados.
        

  schemas:
    HotelesDestinationGet:
      type: object
      properties:
        codigoHotel:
          type: string
          enum: [CH-0002]
          description: Código del hotel a buscar
        nombre:
          type: string
          description: Nombre del hotel
        lugar:
          type: string
          description: Ubicación del hotel
        tipoHabitacion:
          type: string
          description: Tipo de habitación que ofrece el hotel
        precioNoche:
          type: integer
          description: Precio por noche
        disponibleDesde:
          type: string
          format: date
          description: Fecha de inicio de disponibilidad del hotel
        disponibleHasta:
          type: string
          format: date
          description: Fecha de fin de disponibilidad del hotel
        reservado:
          type: boolean
          description: Si está reservado
          
    HotelesLowerCostGet:
        type: object
        properties:
            codigoHotel:
              type: string
              enum: [CH-0002]
              description: Código del hotel a buscar
            nombre:
              type: string
              description: Nombre del hotel
            lugar:
              type: string
              description: Ubicación del hotel
            tipoHabitacion:
              type: string
              description: Tipo de habitación que ofrece el hotel
            precioNoche:
              type: integer
              description: Precio por noche
            disponibleDesde:
              type: string
              format: date
              description: Fecha de inicio de disponibilidad del hotel
            disponibleHasta:
              type: string
              format: date
              description: Fecha de fin de disponibilidad del hotel
            reservado:
              type: boolean
              description: Si está reservado
              
              
    HotelesStaySimulation:
        type: object
        properties:
            Message:
              type: string
              enum: [El costo total de la simulación es de...]
              description: Mensaje devolviendo el costo simulado
            name:
              type: string
              enum: [SIMULACIÓN]
              description: Nombre de la simulación
              
              
              
              
    HotelFindByName:
        type: object
        properties:
            codigoHotel:
              type: string
              enum: [CH-0002]
              description: Código del hotel a buscar
            nombre:
              type: string
              enum: [Nombre del hotel buscado]
              description: Nombre del hotel
            lugar:
              type: string
              description: Ubicación del hotel
            tipoHabitacion:
              type: string
              description: Tipo de habitación que ofrece el hotel
            precioNoche:
              type: integer
              description: Precio por noche
            disponibleDesde:
              type: string
              format: date
              description: Fecha de inicio de disponibilidad del hotel
            disponibleHasta:
              type: string
              format: date
              description: Fecha de fin de disponibilidad del hotel
            reservado:
              type: boolean
              description: Si está reservado